# -*- coding: utf-8 -*-
"""Fine-tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyY57Yr7Xf8lHFviQTy4-6Moo4o6uBRb
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install required packages
!pip install -q transformers accelerate peft bitsandbytes datasets

# Import required libraries
import os
import gc
import torch
import pandas as pd
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    BitsAndBytesConfig,
    DataCollatorForSeq2Seq
)
from transformers.trainer_utils import get_last_checkpoint
from peft import get_peft_model, LoraConfig, TaskType, prepare_model_for_kbit_training

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
torch.manual_seed(42)

# Configuration
# Base (instruct) models
models = {
    "meltemi": "ilsp/Meltemi-7B-Instruct-v1.5",
    "llama_krikri": "ilsp/Llama-Krikri-8B-Instruct"
}

# 1000-review and 2000-review training sets
set_sizes = [1000, 2000]

max_length = 1024

# Fine-tuning will be performed only on the three 0-shot variants
variants = [
    "0_shot_sentiment_only",
    "0_shot_sentiment_then_explanation",
    "0_shot_explanation_then_sentiment"
]

# Prompt template
def prompt_template(review_text, variant):
    base_instruction = (
        "Είσαι ένας ειδικός αναλυτής συναισθημάτων για κριτικές ταινιών.\n"
        "Ανάλυσε προσεκτικά την παρακάτω κριτική ταινίας και καθόρισε ξεκάθαρα αν εκφράζει θετικό ή αρνητικό συναίσθημα.\n"
        f"Κριτική: «{review_text}»\n"
    )
    if variant == "0_shot_sentiment_only":
        # Define a prompt template that instructs the model to identify sentiment
        return base_instruction + (
            "Απάντησε μόνο με μία από τις δύο λέξεις (θετικό ή αρνητικό) με την ακόλουθη μορφή:\n"
            "Συναίσθημα: [θετικό ή αρνητικό]\n"
            "Μην προσθέσεις καμία άλλη λέξη ή εξήγηση.\n"
            "Απάντηση:\n"
        )
    elif variant == "0_shot_sentiment_then_explanation":
        # Define a prompt template that instructs the model to identify sentiment and explain it
        return base_instruction + (
            "Απάντησε υποχρεωτικά και στα δύο ζητούμενα με την ακόλουθη μορφή:\n"
            "Συναίσθημα: [θετικό ή αρνητικό]\n"
            "Εξήγηση: [σύντομη εξήγηση 1-2 προτάσεων]\n"
            "Είναι απαραίτητο να παρέχεις και τα δύο (Συναίσθημα και Εξήγηση).\n"
            "Απάντηση:\n"
        )
    elif variant == "0_shot_explanation_then_sentiment":
        # Define a prompt template that instructs the model to explain sentiment and identify it
        return base_instruction + (
            "Απάντησε υποχρεωτικά και στα δύο ζητούμενα με την ακόλουθη μορφή:\n"
            "Εξήγηση: [σύντομη εξήγηση 1-2 προτάσεων]\n"
            "Συναίσθημα: [θετικό ή αρνητικό]\n"
            "Είναι απαραίτητο να παρέχεις και τα δύο (Εξήγηση και Συναίσθημα).\n"
            "Απάντηση:\n"
        )
    else:
        raise ValueError(f"Unknown variant: {variant}")

# Answer composition
def compose_answer(variant, sentiment, explanation):
    if variant == "0_shot_sentiment_only":
        return f"Συναίσθημα: {sentiment}"
    elif variant == "0_shot_sentiment_then_explanation":
        return f"Συναίσθημα: {sentiment}\nΕξήγηση: {explanation}"
    elif variant == "0_shot_explanation_then_sentiment":
        return f"Εξήγηση: {explanation}\nΣυναίσθημα: {sentiment}"
    else:
        raise ValueError(f"Unknown variant: {variant}")

def build_example(df, explanation, variants):
    # Each review becomes one training example per variant (variants with explanation generation need a non-empty explanation)
    examples = []
    for _, row in df.iterrows():
        review = row["review"]
        sentiment = row["sentiment"]
        explanation = row.get(explanation, "")
        has_explanation = isinstance(explanation, str) and explanation.strip() != ""
        for variant in variants:
            if variant != "0_shot_sentiment_only" and not has_explanation:
                continue
            examples.append({
                "prompt": prompt_template(review, variant),
                "answer": compose_answer(variant, sentiment, explanation)
            })
    return examples

# Supervised tokenization: loss only on the answer, which is never truncated
def tokenize_supervised(example, tokenizer, max_length=1024):
    prompt = example["prompt"]
    answer = f"{example['answer']}{tokenizer.eos_token}"

    prompt_ids = tokenizer(prompt, add_special_tokens=True)["input_ids"]
    answer_ids = tokenizer(answer, add_special_tokens=False)["input_ids"]

    # If too long, trim the prompt from the left, never trim the answer
    max_prompt = max(1, max_length - len(answer_ids))
    if len(prompt_ids) > max_prompt:
        prompt_ids = [prompt_ids[0]] + prompt_ids[-(max_prompt - 1):]

    input_ids = prompt_ids + answer_ids

    # -100 is ignored by the loss, so the model is fine-tuned only on the answer
    labels = [-100] * len(prompt_ids) + answer_ids
    attention_mask = [1] * len(input_ids)
    return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}

# 4-bit quantization (QLoRA) and LoRA configuration
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
)

def adapter_exists(output_directory: str) -> bool:
    return (
        os.path.exists(os.path.join(output_directory, "adapter_config.json")) and
        (
            os.path.exists(os.path.join(output_directory, "adapter_model.safetensors")) or
            os.path.exists(os.path.join(output_directory, "adapter_model.bin"))
        )
    )

# Fine-tuning loop
for model_name, model_id in models.items():
    print(f"\n{'='*60}\nFine-tuning: {model_name}\n{'='*60}")

    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    column = f"{model_name}_explanation"

    for set_size in set_sizes:
        output_directory = f"/content/drive/MyDrive/MSc Thesis/{model_name}_{set_size}"
        os.makedirs(output_directory, exist_ok=True)

        # Skip, if this adapter has already been fully fine-tuned
        if adapter_exists(output_directory):
            print(f"\n{model_name} {set_size}: adapter already exists, skipping -> {output_directory}")
            continue

        # Resume, if a previous run was interrupted during fine-tuning
        last_checkpoint = get_last_checkpoint(output_directory)
        if last_checkpoint:
            print(f"\n{model_name} {set_size}: resuming from last checkpoint {last_checkpoint}")
        else:
            print(f"\n{model_name} {set_size}: training from scratch")

        # Explanation-augmented data for this set_size
        csv_path = f"/content/drive/MyDrive/MSc Thesis/sample_training_data_{set_size}_explanations.csv"
        df = pd.read_csv(csv_path).dropna(subset=["review", "sentiment"])
        if column not in df.columns:
            raise ValueError(
                f"Column '{column}' not found in {csv_path}. "
                f"Run Training Explanations Generation.ipynb first."
            )

        examples = build_example(df, column, variants)
        print(f"{model_name} {set_size}: {len(df)} reviews -> {len(examples)} training examples")

        dataset = Dataset.from_list(examples).train_test_split(test_size=0.1, seed=42)
        tokenized = dataset.map(
            lambda x: tokenize_supervised(x, tokenizer, max_length=max_length),
            remove_columns=["prompt", "answer"]
        )

        gc.collect()
        torch.cuda.empty_cache()

        # Fresh 4-bit base (instruct) model and LoRA adapters for each run
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            quantization_config=bnb_config,
            device_map="auto",
            low_cpu_mem_usage=True
        )
        model.config.use_cache = False
        model = prepare_model_for_kbit_training(model)
        model.gradient_checkpointing_enable()
        model = get_peft_model(model, peft_config)

        training_args = TrainingArguments(
            output_dir=output_directory,
            per_device_train_batch_size=2,
            per_device_eval_batch_size=2,
            gradient_accumulation_steps=4,
            num_train_epochs=3,
            learning_rate=2e-4,
            logging_steps=10,
            eval_strategy="steps",
            eval_steps=200,
            save_strategy="steps",
            save_steps=200,
            save_total_limit=2,
            fp16=True,
            report_to="none",
            remove_unused_columns=False,
            load_best_model_at_end=False
        )

        # Dynamic padding; pads labels with -100 automatically
        data_collator = DataCollatorForSeq2Seq(
            tokenizer=tokenizer,
            model=model,
            padding=True,
            return_tensors="pt"
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=tokenized["train"],
            eval_dataset=tokenized["test"],
            data_collator=data_collator
        )

        trainer.train(resume_from_checkpoint=last_checkpoint)

        # Save the final LoRA adapter and tokenizer into output_directory
        model.save_pretrained(output_directory)
        tokenizer.save_pretrained(output_directory)
        print(f"{model_name} {set_size}: saved adapter -> {output_directory}")

        # Free VRAM before the next run
        del trainer, model, tokenized, dataset, df, examples
        gc.collect()
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()