# -*- coding: utf-8 -*-
"""Meltemi Fine-tuned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vyuRatqUVnlZ8REy8Ejx2gKk-B5qcBuw
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install required packages
!pip install -q transformers accelerate peft bitsandbytes tqdm scikit-learn

# Import required libraries
from tqdm import tqdm
import pandas as pd
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
from sklearn.metrics import precision_score, recall_score, f1_score
import gc
import torch
import unicodedata
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
torch.manual_seed(42)

# Instruction-tuned model
instruction_tuned_model = "ilsp/Meltemi-7B-Instruct-v1.5"

# Each folder contains a fine-tuned Meltemi model adapter and its tokenizer
adapter_folders = [
    "/content/drive/MyDrive/MSc Thesis/meltemi_1000",
    "/content/drive/MyDrive/MSc Thesis/meltemi_2000"
]

# Load model, tokenizer and adapter_folder_name
def load_model_tokenizer_and_adapter_folder_name(instruction_tuned_model, adapter_folder):
    adapter_folder_name = os.path.basename(adapter_folder)

    tokenizer = AutoTokenizer.from_pretrained(adapter_folder, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True
    )

    model = AutoModelForCausalLM.from_pretrained(
        instruction_tuned_model,
        quantization_config=bnb_config,
        device_map="auto",
        dtype=torch.float16
    )

    model = PeftModel.from_pretrained(
        model,
        adapter_folder
    )

    model.eval()
    return model, tokenizer, adapter_folder_name

# Load the test dataset from Google Drive
test_df = pd.read_csv("/content/drive/MyDrive/MSc Thesis/sample_test_dataset.csv")

# Preview the first few and the last few rows
print(test_df.head())
print("\n")
print(test_df.tail())

# File path
def file_path(task, adapter_folder_name):
  if task == "0_shot_sentiment_only":
    # Define file paths for saving outputs during and after execution
    checkpoint_path = f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_sentiment_only_checkpoint.csv"
    final_output_path = f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_sentiment_only_final.csv"
  elif task == "0_shot_sentiment_then_explanation":
    # Define file paths for saving outputs during and after execution
    checkpoint_path = f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_sentiment_then_explanation_checkpoint.csv"
    final_output_path = f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_sentiment_then_explanation_final.csv"
  elif task == "0_shot_explanation_then_sentiment":
    # Define file paths for saving outputs during and after execution
    checkpoint_path = f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_explanation_then_sentiment_checkpoint.csv"
    final_output_path = f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_explanation_then_sentiment_final.csv"
  else:
    raise ValueError(f"Unknown task: {task}")
  return checkpoint_path, final_output_path

# Prompt template
def prompt_template(review_text, task):
    base_instruction = (
        "Είσαι ένας ειδικός αναλυτής συναισθημάτων για κριτικές ταινιών.\n"
        "Ανάλυσε προσεκτικά την παρακάτω κριτική ταινίας και καθόρισε ξεκάθαρα αν εκφράζει θετικό ή αρνητικό συναίσθημα.\n"
        f"Κριτική: «{review_text}»\n"
    )

    if task == "0_shot_sentiment_only":
        # Define a prompt template that instructs the model to identify sentiment
        return base_instruction + (
            "Απάντησε μόνο με μία από τις δύο λέξεις (θετικό ή αρνητικό) με την ακόλουθη μορφή:\n"
            "Συναίσθημα: [θετικό ή αρνητικό]\n"
            "Μην προσθέσεις καμία άλλη λέξη ή εξήγηση.\n"
            "Απάντηση:\n"
        )
    elif task == "0_shot_sentiment_then_explanation":
        # Define a prompt template that instructs the model to identify sentiment and explain it
        return base_instruction + (
            "Απάντησε υποχρεωτικά και στα δύο ζητούμενα με την ακόλουθη μορφή:\n"
            "Συναίσθημα: [θετικό ή αρνητικό]\n"
            "Εξήγηση: [σύντομη εξήγηση 1-2 προτάσεων]\n"
            "Είναι απαραίτητο να παρέχεις και τα δύο (Συναίσθημα και Εξήγηση).\n"
            "Απάντηση:\n"
        )
    elif task == "0_shot_explanation_then_sentiment":
        # Define a prompt template that instructs the model to explain sentiment and identify it
        return base_instruction + (
            "Απάντησε υποχρεωτικά και στα δύο ζητούμενα με την ακόλουθη μορφή:\n"
            "Εξήγηση: [σύντομη εξήγηση 1-2 προτάσεων]\n"
            "Συναίσθημα: [θετικό ή αρνητικό]\n"
            "Είναι απαραίτητο να παρέχεις και τα δύο (Εξήγηση και Συναίσθημα).\n"
            "Απάντηση:\n"
        )
    else:
      raise ValueError(f"Unknown task: {task}")

# Checkpointing
def checkpoint(checkpoint_path):
  # Load previous results from checkpoint, if it exists
  if os.path.exists(checkpoint_path):
    results_df = pd.read_csv(checkpoint_path)
    processed_reviews = set(results_df["greek_review"])
    print(f"Resuming from checkpoint. Already processed: {len(processed_reviews)} reviews.")
  else:
    results_df = pd.DataFrame(columns=["greek_review", "model_output"])
    processed_reviews = set()
  return results_df, processed_reviews

# Generation
def generate(model, tokenizer, prompt, max_new_tokens=200):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    # Greedy decoding, stopping at any of the model's own end tokens
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_ids = outputs[0][inputs["input_ids"].shape[1]:]
    answer = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()
    return answer

# Prediction
def predict(test_df, model, tokenizer, prompt_template, checkpoint_path, final_output_path, processed_reviews, results_df, task):
  new_rows = []

  # Iterate through the test dataset with progress bar
  for i, row in tqdm(test_df.iterrows(), total=len(test_df)):
    review = row["translation"]

    # Skip, if this review has already been processed in a previous run (checkpointing)
    if review in processed_reviews:
      continue

    prompt = prompt_template(review, task)

    try:
      # Run the fine-tuned Meltemi model with the generated prompt
      answer = generate(model, tokenizer, prompt, max_new_tokens=200)
    # If an error occurs during generation, store the error message instead
    except Exception as e:
        answer = f"Error: {e}"

    # Store the review and model's response in dictionary format
    new_rows.append({
        "greek_review": review,
        "model_output": answer
    })

    # Save a checkpoint every 10 samples to prevent data loss
    if i % 10 == 0:
      pd.concat([results_df, pd.DataFrame(new_rows)], ignore_index=True).to_csv(checkpoint_path, index=False)

  # Final save after the loop ends
  results_df = pd.concat([results_df, pd.DataFrame(new_rows)], ignore_index=True)
  results_df.to_csv(checkpoint_path, index=False)
  results_df.to_csv(final_output_path, index=False)

# Output
def output(task, adapter_folder_name):
  if task == "0_shot_sentiment_only":
    # Load the output of fine-tuned Meltemi model from Google Drive
    output_df = pd.read_csv(f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_sentiment_only_final.csv")
  elif task == "0_shot_sentiment_then_explanation":
    # Load the output of fine-tuned Meltemi model from Google Drive
    output_df = pd.read_csv(f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_sentiment_then_explanation_final.csv")
  elif task == "0_shot_explanation_then_sentiment":
    # Load the output of fine-tuned Meltemi model from Google Drive
    output_df = pd.read_csv(f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_0_shot_explanation_then_sentiment_final.csv")
  else:
    raise ValueError(f"Unknown task: {task}")
  return output_df

# Merging
def merge(output_df, test_df):
  # Merge on greek_review to align predictions with true labels
  merged_df = pd.merge(output_df, test_df, left_on="greek_review", right_on="translation")
  return merged_df

# Sentiment extraction
def extract_sentiment(output, task):
    if not isinstance(output, str):
        output = str(output)

    # Clean the output
    text = output.lower().strip()

    # Remove accents for more robust matching
    text = unicodedata.normalize('NFD', text)
    text = ''.join(c for c in text if unicodedata.category(c) != 'Mn')

    # For structured output, look for patterns
    if 'συναισθημα:' in text:
        sentiment_line = text.split('συναισθημα:')[1].split('\n')[0].strip()
        if any(word in sentiment_line for word in ['θετικ', 'positive']):
            return "positive"
        elif any(word in sentiment_line for word in ['αρνητικ', 'negative']):
            return "negative"

    # Fallback to general pattern matching
    if 'θετικ' in text:
        return "positive"
    elif 'αρνητικ' in text:
        return "negative"
    else:
        return "unknown"

# Evaluation
def evaluate(merged_df, path, task):
    # Apply extraction
    merged_df["predicted_sentiment"] = merged_df["model_output"].apply(lambda x: extract_sentiment(x, task))

    # Calculate basic metrics
    merged_df["correct"] = merged_df["predicted_sentiment"] == merged_df["sentiment"]
    accuracy = merged_df["correct"].mean()

    # Count unknowns
    unknown_count = (merged_df["predicted_sentiment"] == "unknown").sum()
    unknown_rate = unknown_count / len(merged_df)

    print(f"Task: {task}")
    print(f"Accuracy: {accuracy * 100:.2f}%")
    print(f"Unknown predictions: {unknown_count}/{len(merged_df)} ({unknown_rate * 100:.2f}%)")

    # Detailed analysis (excluding unknowns)
    mask = merged_df["predicted_sentiment"] != "unknown"
    if mask.sum() > 0:
        # True labels
        y_true = merged_df.loc[mask, "sentiment"]
        # Predicted labels
        y_pred = merged_df.loc[mask, "predicted_sentiment"]

        # Calculate metrics for both classes (positive/negative)
        precision_pos = precision_score(y_true, y_pred, pos_label="positive", average="binary")
        recall_pos = recall_score(y_true, y_pred, pos_label="positive", average="binary")
        f1_pos = f1_score(y_true, y_pred, pos_label="positive", average="binary")

        precision_neg = precision_score(y_true, y_pred, pos_label="negative", average="binary")
        recall_neg = recall_score(y_true, y_pred, pos_label="negative", average="binary")
        f1_neg = f1_score(y_true, y_pred, pos_label="negative", average="binary")

        print(f"Positive class - Precision: {precision_pos:.3f}, Recall: {recall_pos:.3f}, F1: {f1_pos:.3f}")
        print(f"Negative class - Precision: {precision_neg:.3f}, Recall: {recall_neg:.3f}, F1: {f1_neg:.3f}")

        # Macro averages
        macro_f1 = f1_score(y_true, y_pred, average="macro")
        print(f"Macro F1: {macro_f1:.3f}")

    # Save results
    merged_df.to_csv(path, index=False)
    print(f"Results saved to: {path}\n")

# Explanation analysis
def analyze_explanation(merged_df, task):
  if 'explanation' not in task:
    return

  explanations = []
  for output in merged_df["model_output"]:
    if isinstance(output, str):
      # Clean the output
      text = output.lower().strip()

      # Remove accents for more robust matching
      text = unicodedata.normalize('NFD', text)
      text = ''.join(c for c in text if unicodedata.category(c) != 'Mn')

      if 'εξηγηση:' in text:
        explanation = text.split('εξηγηση:')[1].split('\n')[0].strip()
        explanations.append(len(explanation.split()))
      else:
        explanations.append(0)
    else:
      explanations.append(0)

  merged_df["explanation_length"] = explanations
  # Calculate the average word count
  avg_length = sum(explanations) / len(explanations) if explanations else 0
  print(f"Average explanation length: {avg_length:.1f} words")

# Experimentation
def run_experiment(task, adapter_folder_name):
    print(f"\n{'='*50}")
    print(f"Running task: {task}")
    print('='*50)

    checkpoint_path, final_output_path = file_path(task, adapter_folder_name)

    results_df, processed_reviews = checkpoint(checkpoint_path)

    predict(test_df, model, tokenizer, prompt_template, checkpoint_path, final_output_path, processed_reviews, results_df, task)

    output_df = output(task, adapter_folder_name)

    merged_df = merge(output_df, test_df)

    eval_path = f"/content/drive/MyDrive/MSc Thesis/Test/{adapter_folder_name}_{task}_eval.csv"

    evaluate(merged_df, eval_path, task)

    # Add explanation analysis for relevant tasks
    if 'explanation' in task:
        analyze_explanation(merged_df, task)

    return merged_df


# Run all experiments
variants = [
    "sentiment_only",
    "sentiment_then_explanation",
    "explanation_then_sentiment"
]

results = {}

for adapter_folder in adapter_folders:
    print(f"\n{'='*50}")
    print(f"Loading fine-tuned Meltemi model from: {adapter_folder}")
    print(f"{'='*50}\n")

    model, tokenizer, adapter_folder_name = load_model_tokenizer_and_adapter_folder_name(instruction_tuned_model, adapter_folder)

    results[adapter_folder_name] = {}

    for variant in variants:
        task = f"0_shot_{variant}"
        results[adapter_folder_name][task] = run_experiment(task, adapter_folder_name)

    # Free VRAM before the next run
    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()