# -*- coding: utf-8 -*-
"""Training Explanations Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdL4dMnxOyiBt4eay6f7BQlKlI1OYHEG
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install required packages
!pip install -q transformers accelerate bitsandbytes

# Import required libraries
import os
import gc
import torch
import pandas as pd
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
torch.manual_seed(42)

# Configuration
# Base (instruct) models; each one explains its own training data
models = {
    "meltemi": "ilsp/Meltemi-7B-Instruct-v1.5",
    "llama_krikri": "ilsp/Llama-Krikri-8B-Instruct"
}

# 2000-review training set is processed first, so the 1000-review training set reuses its explanations (no re-generation)
set_sizes = [2000, 1000]

max_new_tokens = 100

save_every = 20

def original_path(set_size):
    return f"/content/drive/MyDrive/MSc Thesis/sample_training_data_{set_size}.csv"

def augmented_path(set_size):
    return f"/content/drive/MyDrive/MSc Thesis/sample_training_data_{set_size}_explanations.csv"

# Load a base (instruct) model in 4-bit
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

def load_base_model(model_id):
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        device_map="auto"
    )
    model.eval()
    return model, tokenizer

# Training explanation generation, conditioned on the gold sentiment
def prompt_template(review_text, sentiment):
    return (
        "Είσαι ένας ειδικός αναλυτής συναισθημάτων για κριτικές ταινιών.\n"
        f"Η παρακάτω κριτική ταινίας εκφράζει {sentiment} συναίσθημα.\n"
        f"Κριτική: «{review_text}»\n"
        f"Γράψε μια σύντομη εξήγηση 1-2 προτάσεων για το γιατί η κριτική ταινίας εκφράζει {sentiment} συναίσθημα.\n"
        "Απάντησε με την ακόλουθη μορφή:\n"
        "Εξήγηση: [σύντομη εξήγηση 1-2 προτάσεων]\n"
        "Απάντηση:\n"
    )

def clean_explanation(text):
    text = text.strip()
    # Drop a leading "Εξήγηση:", if the model echoed it
    if text.lower().startswith("εξήγηση:"):
        text = text.split(":", 1)[1].strip()
    # Stop at any hallucinated continuation of the prompt template
    for stop in ["\nΚριτική", "\nΣυναίσθημα", "Κριτική:", "Συναίσθημα:"]:
        idx = text.find(stop)
        if idx != -1:
            text = text[:idx].strip()
    # Collapse newlines/extra spaces into single spaces
    text = " ".join(text.split())
    return text

@torch.no_grad()
def generate_explanation(model, tokenizer, review_text, sentiment):
    prompt = prompt_template(review_text, sentiment)
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=2048).to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id,
        eos_token_id=tokenizer.eos_token_id
    )
    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]
    answer = tokenizer.decode(generated_tokens, skip_special_tokens=True)
    return clean_explanation(answer)

# Each model explains its own training data
def incomplete_column(path, column):
    if not os.path.exists(path):
        return True
    df = pd.read_csv(path)
    if column not in df.columns:
        return True
    return df[column].isna().any() or (df[column].astype(str).str.strip() == "").any()

for model_name, model_id in models.items():
    column = f"{model_name}_explanation"

    # Skip this model, if every file already has the relevant column (explanation column) fully filled
    if not any(incomplete_column(augmented_path(set_size), column) for set_size in set_sizes):
        print(f"{model_name}: all explanations already present, skipping.")
        continue

    print(f"\n{'='*60}\nGenerating training explanations with: {model_name}\n{'='*60}")
    model, tokenizer = load_base_model(model_id)

    # Warm a cache so reviews shared across the 1000-review and 2000-review training sets are reused (no re-generation)
    cache = {}
    for set_size in set_sizes:
        path = augmented_path(set_size)
        if os.path.exists(path):
            df = pd.read_csv(path)
            if column in df.columns:
                for review_text, explanation in zip(df["review"], df[column]):
                    if isinstance(explanation, str) and explanation.strip():
                        cache[review_text] = explanation

    for set_size in set_sizes:
        # Load the augmented path's file, if it exists (keeps the other model's column), else the original path's file
        if os.path.exists(augmented_path(set_size)):
            df = pd.read_csv(augmented_path(set_size))
        else:
            df = pd.read_csv(original_path(set_size)).dropna(subset=["review", "sentiment"]).reset_index(drop=True)
        if column not in df.columns:
            df[column] = ""

        to_do = [i for i in range(len(df))
                if not (isinstance(df.at[i, column], str) and df.at[i, column].strip())]
        print(f"{model_name} | {set_size}: {len(to_do)} to generate, {len(df) - len(to_do)} already done")

        for n, i in enumerate(tqdm(to_do)):
            review = df.at[i, "review"]
            sentiment = df.at[i, "sentiment"]
            if review in cache:
                df.at[i, column] = cache[review]
            else:
                explanation = generate_explanation(model, tokenizer, review, sentiment)
                df.at[i, column] = explanation
                cache[review] = explanation
            if n % save_every == 0:
                df.to_csv(augmented_path(set_size), index=False)

        df.to_csv(augmented_path(set_size), index=False)
        print(f"{model_name} | {set_size}: saved -> {augmented_path(set_size)}")

    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

print("\nDone generating training explanations.")