# -*- coding: utf-8 -*-
"""Training Explanations Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdL4dMnxOyiBt4eay6f7BQlKlI1OYHEG
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install required packages
!pip install -q transformers accelerate bitsandbytes

# Import required libraries
import os
import gc
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
import torch
import pandas as pd
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

# Configuration
# Instruction-tuned models
models = {
    "meltemi": "ilsp/Meltemi-7B-Instruct-v1.5",
    "llama_krikri": "ilsp/Llama-Krikri-8B-Instruct"
}

# 2000-review training set is processed first, so the 1000-review training set reuses its explanations (no re-generation)
set_sizes = [2000, 1000]

max_new_tokens = 160

max_review_tokens = 1024

save_every = 20

def original_path(set_size):
    return f"/content/drive/MyDrive/MSc Thesis/sample_training_data_{set_size}.csv"

def explanations_path(set_size):
    return f"/content/drive/MyDrive/MSc Thesis/sample_training_data_{set_size}_explanations.csv"

# 4-bit NF4 quantization, so both models fit in VRAM
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

# Load model and tokenizer
def load_model_and_tokenizer(model_id):
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        device_map="auto"
    )
    model.eval()
    # Report the stop tokens, so it is clear where generation is expected to end
    print(f"eos_token: {tokenizer.eos_token} - eos_token_id: ({tokenizer.eos_token_id}) - generation_config eos_token_id: {model.generation_config.eos_token_id}")
    return model, tokenizer

# Cap the review, so the instruction at the end of the prompt is never truncated away
def truncate_review(tokenizer, review_text):
    ids = tokenizer(review_text, add_special_tokens=False)["input_ids"]
    if len(ids) <= max_review_tokens:
        return review_text
    return tokenizer.decode(ids[:max_review_tokens], skip_special_tokens=True)

# Prompt template
def prompt_template(review_text, sentiment_label):
    return (
        "Είσαι ένας ειδικός αναλυτής συναισθημάτων για κριτικές ταινιών.\n"
        f"Η παρακάτω κριτική ταινίας εκφράζει {sentiment_label} συναίσθημα.\n"
        f"Κριτική: «{review_text}»\n"
        f"Γράψε μία σύντομη εξήγηση 1-2 προτάσεων σχετικά με το γιατί η παραπάνω κριτική ταινίας εκφράζει {sentiment_label} συναίσθημα.\n"
        "Απάντησε με την ακόλουθη μορφή:\n"
        "Εξήγηση: [σύντομη εξήγηση 1-2 προτάσεων]\n"
        "Απάντηση:\n"
    )

# Clean the explanation
def clean_explanation(text):
    if not isinstance(text, str):
        text = str(text)
    explanation = text.strip()
    # Drop a leading "Εξήγηση:", if the model echoed it
    if explanation.lower().startswith("εξήγηση:"):
        explanation = explanation.split(":", 1)[1].strip()
    # Stop at any hallucinated continuation of the prompt
    for stop in ["Κριτική:", "Συναίσθημα:", "Εξήγηση:"]:
        idx = explanation.find(stop)
        if idx > 0:
            explanation = explanation[:idx].strip()
    # Collapse newlines/extra spaces into single spaces
    explanation = " ".join(explanation.split())
    return explanation

# Drop a trailing sentence fragment left behind by the max_new_tokens cap
def drop_incomplete_sentence(explanation):
    if explanation and explanation[-1] not in ".!;…":
        cut = max(explanation.rfind(c) for c in ".!;…")
        if cut > 0:
            explanation = explanation[:cut + 1]
    return explanation

@torch.no_grad()
def generate_explanation(model, tokenizer, review_text, sentiment_label):
    prompt = prompt_template(truncate_review(tokenizer, review_text), sentiment_label)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )
    generated_ids = outputs[0][inputs["input_ids"].shape[1]:]
    # Let the model's own generation_config supply the stop tokens
    eos_ids = model.generation_config.eos_token_id or tokenizer.eos_token_id
    eos_ids = eos_ids if isinstance(eos_ids, (list, tuple)) else [eos_ids]
    hit_cap = (generated_ids.shape[0] >= max_new_tokens
               and generated_ids[-1].item() not in eos_ids)
    answer = tokenizer.decode(generated_ids, skip_special_tokens=True)
    explanation = clean_explanation(answer)
    return drop_incomplete_sentence(explanation) if hit_cap else explanation

# Each model explains its own training data
def incomplete_column(path, explanations_column):
    if not os.path.exists(path):
        return True
    df = pd.read_csv(path)
    if explanations_column not in df.columns:
        return True
    return df[explanations_column].isna().any() or (df[explanations_column].astype(str).str.strip() == "").any()

for model_name, model_id in models.items():
    explanations_column = f"{model_name}_explanation"

    # Skip this model, if every file already has the explanation column fully filled
    if not any(incomplete_column(explanations_path(set_size), explanations_column) for set_size in set_sizes):
        print(f"{model_name}: all explanations already present, skipping.")
        continue

    print(f"\n{'='*60}\nGenerating training explanations with: {model_name}\n{'='*60}")
    model, tokenizer = load_model_and_tokenizer(model_id)

    # Warm a cache, so reviews' explanations shared across the 1000-review and 2000-review training sets are reused (no re-generation)
    cache = {}
    for set_size in set_sizes:
        path = explanations_path(set_size)
        if os.path.exists(path):
            df = pd.read_csv(path)
            if explanations_column in df.columns:
                for review_text, explanation in zip(df["review"], df[explanations_column]):
                    if isinstance(explanation, str) and explanation.strip():
                        cache[review_text] = explanation

    for set_size in set_sizes:
        # Load the explanations path's file, if it exists (keeps the other model's explanation column), else the original path's file
        if os.path.exists(explanations_path(set_size)):
            df = pd.read_csv(explanations_path(set_size))
        else:
            df = pd.read_csv(original_path(set_size)).dropna(subset=["review", "sentiment"]).reset_index(drop=True)
        if explanations_column not in df.columns:
            df[explanations_column] = ""

        to_do = [i for i in range(len(df)) if not (isinstance(df.at[i, explanations_column], str) and df.at[i, explanations_column].strip())]
        print(f"{model_name} - {set_size}: {len(to_do)} to generate, {len(df) - len(to_do)} already done")

        for n, i in enumerate(tqdm(to_do)):
            review_text = df.at[i, "review"]
            sentiment_label = df.at[i, "sentiment"]
            if review_text in cache:
                df.at[i, explanations_column] = cache[review_text]
            else:
                explanation = generate_explanation(model, tokenizer, review_text, sentiment_label)
                df.at[i, explanations_column] = explanation
                if explanation:
                    cache[review_text] = explanation
            if (n + 1) % save_every == 0:
                df.to_csv(explanations_path(set_size), index=False)

        df.to_csv(explanations_path(set_size), index=False)
        empty_explanations = int((df[explanations_column].isna() | (df[explanations_column].astype(str).str.strip() == "")).sum())
        print(f"{model_name} - {set_size}: saved -> {explanations_path(set_size)}, ({empty_explanations} empty explanations of {len(df)})")

    # Free VRAM before the next run
    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

print("\nDone generating training explanations.")